# Generated by Django 4.1.9 on 2023-05-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_background_color_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#357e40', max_length=7),
        ),
    ]
