# Generated by Django 4.1.9 on 2023-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile_images/Hotpot (13).png', upload_to='profile_images/'),
        ),
    ]
