# Generated by Django 4.1.9 on 2023-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile_images/default_profile_image.png', upload_to='profile_images/'),
        ),
    ]
