# Generated by Django 4.1.9 on 2023-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accounts/default_profile_images')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to='accounts/profile_images'),
        ),
    ]
