# Generated by Django 4.1.9 on 2023-06-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_defaultprofileimage_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultProfileImage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='791498.png', upload_to='accounts/avatars'),
        ),
    ]
